version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: flavio
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: flaviodb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
